# Generated by Django 5.1.7 on 2025-03-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Discount'),
        ),
    ]
