# Generated by Django 5.1.7 on 2025-03-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
