# Generated by Django 5.1.7 on 2025-03-31 18:51

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productvariation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='price_cents',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='sku', unique=True),
        ),
    ]
