# Generated by Django 5.1.7 on 2025-03-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productvariation_price_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
