# Generated by Django 5.1.7 on 2025-04-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productvariation_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Discount'),
        ),
    ]
