# Generated by Django 5.1.7 on 2025-04-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productvariation_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
