# Generated by Django 5.1.7 on 2025-04-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_is_active_productvariation_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'ordering': ['product', 'color'], 'verbose_name': 'product variation', 'verbose_name_plural': 'product variations'},
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'color')},
        ),
        migrations.AddField(
            model_name='productvariation',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='store.size'),
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='size',
        ),
    ]
