# Generated by Django 5.1.7 on 2025-04-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_size_alter_productvariation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='sizes',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.size'),
            preserve_default=False,
        ),
    ]
