# Generated by Django 5.1.7 on 2025-04-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_productvariation_sizes_productvariation_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'color', 'size')},
        ),
    ]
